base_model = "tencent/hy3-preview"
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["none", "low", "high"]

[cost]
input = 0.063
output = 0.21
cache_read = 0.021
discount = 0.65
input_list = 0.18
output_list = 0.6
cache_read_list = 0.06

[limit]
context = 262_144
output = 262_144
