base_model = "minimax/MiniMax-M2.5"
structured_output = true
reasoning_options = []

[interleaved]
field = "reasoning_details"

[cost]
input = 0.27
output = 1.08
cache_read = 0.027
discount = 0.1
input_list = 0.3
output_list = 1.2
cache_read_list = 0.03

[limit]
output = 128_000
