base_model = "deepseek/deepseek-chat"
attachment = false
structured_output = true

[cost]
input = 0.2574
output = 1.0287
discount = 0.1
input_list = 0.286
output_list = 1.143

[limit]
context = 163_840
output = 16_000
