base_model = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.07266
output = 0.14532
cache_read = 0.014532
discount = 0.481
input_list = 0.14
output_list = 0.28
cache_read_list = 0.028

[limit]
context = 1_048_576
