base_model = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.07938
output = 0.15876
cache_read = 0.015876
discount = 0.411
input_list = 0.134771
output_list = 0.269542
cache_read_list = 0.026954

[limit]
context = 1_048_576
