base_model = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.06706
output = 0.13412
cache_read = 0.013412
discount = 0.519
input_list = 0.139418
output_list = 0.278836
cache_read_list = 0.027884

[limit]
context = 1_048_576
