base_model = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.268482
output = 0.536964
cache_read = 0.022374
discount = 0.455
input_list = 0.492628
output_list = 0.985255
cache_read_list = 0.041053

[limit]
context = 1_048_576
