base_model = "deepseek/deepseek-v4-pro-0813"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.57948
output = 1.73844
cache_read = 0.019316
discount = 0.561
input_list = 1.32
output_list = 3.96
cache_read_list = 0.044

[limit]
context = 1_048_576
