base_model = "deepseek/deepseek-v4-flash-0731"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.0658
output = 0.1316
cache_read = 0.01316
discount = 0.53
input_list = 0.14
output_list = 0.28
cache_read_list = 0.028

[limit]
context = 1_310_720
output = 131_072
