base_model = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.647106
output = 1.294212
cache_read = 0.053926
discount = 0.6223
input_list = 1.71328
output_list = 3.426561
cache_read_list = 0.142775

[limit]
context = 1_048_576
